### ISSUE TITLE
[Suggestion] Savestates/Checkpoint selection?

### ISSUE THREAD

**Issue by PavloveVR** [Micrologist/GhostrunnerTrainer#1]
Noticed during practice there were fights you could finish, but couldn't repeat. Would be helpful to be able to toggle your current checkpoint forward or back in the level.

**Comment by Micrologist** [comment]
From my understanding the game doesn't ever store more than one checkpoint. When you hit a checkpoint trigger, it will take a snapshot of the current world state. And whenever you reload checkpoint, it resets your character to that position and restores the world to the snapshot.
There is code in the game to create arbitrary checkpoints at any point, but those will be overwritten if you hit any normal checkpoint triggers.

There probably is a way to make multiple custom checkpoints work but it's very much out of my reach in terms of time and knowledge required.

My suggested workaround for the issue is to just save your position, restart the level, and then teleport back to the location - in most cases this should reset the fights in question.
