### ISSUE TITLE
Speed in the overlay?

### ISSUE THREAD

**Issue by DanzoGit** [Micrologist/GhostrunnerTrainer#2]
Can you display the speed in the overlay?
Yes, I know that this function is in the LiveSplit, but it is not implemented conveniently enough there.
Thanks.

**Comment by Micrologist** [comment]
I'm not sure what overlay you are talking about.

**Comment by DanzoGit** [comment]
Sorry my english is bad.
The current speed of the player.
![grtr](https://user-images.githubusercontent.com/61109303/98440751-813a5880-2135-11eb-83a5-65d709ea6ef6.png)

**Comment by Micrologist** [comment]
Okay, you mean generating an actual overlay on top of the game's window. This is probably not going to happen, mostly because it's way out of my skill area, also C# is probably not a good language for hooking into dx draw calls. Although if anyone else wants to work on this I'd be happy to take a look and possibly integrate it into the trainer.
